apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: istio
spec:
  addonRef:
    name: istio
  clusters:
    - selector:
        matchLabels:
          cluster.x-k8s.io/cluster-name: REPLACE_CLUSTER_NAME
