apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: infra-fbhdn
spec:
  description: Platform infrastructure project for managing VKS clusters and Supervisor resources
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
      name: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
