apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-apps
  namespace: infra-fbhdn
spec:
  description: Tenant applications project scoped to bookstore, reader, and chatbot namespaces on workload clusters
  sourceRepos:
    - 'https://github.com/tmm-demo-apps/*'
  destinations:
    - namespace: bookstore
      name: vks-argo
    - namespace: reader
      name: vks-argo
    - namespace: chatbot
      name: vks-argo
    - namespace: infra-fbhdn
      name: supervisor
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
