apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-2r8k2
resources:
  - ../../base
namePrefix: vks-argo-
patches:
  - target:
      kind: AddonInstall
    patch: |-
      - op: replace
        path: /spec/clusters/0/selector/matchLabels/cluster.x-k8s.io~1cluster-name
        value: vks-argo
