apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infra
  namespace: infra-fbhdn
spec:
  project: default
  source:
    repoURL: https://github.com/tmm-demo-apps/vcf-demo-infra.git
    targetRevision: HEAD
    path: argocd
  destination:
    name: in-cluster
    namespace: infra-fbhdn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
