apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: REPLACE_CLUSTER_NAME
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    classRef:
      name: builtin-generic-v3.7.0
      namespace: vmware-system-vks-public
    version: v1.36.2---vmware.2-vkr.3
    variables:
      - name: vmClass
        value: best-effort-large
      - name: storageClass
        value: vsan-default-storage-policy
      - name: vsphereOptions
        value:
          persistentVolumes:
            defaultStorageClass: vsan-default-storage-policy
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: >-
            os-name=ubuntu,
            os-version=24.04
    workers:
      machineDeployments:
        - class: node-pool
          name: vks-ubuntu-np
          metadata:
            annotations:
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: '3'
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: '2'
              run.tanzu.vmware.com/resolve-os-image: >-
                os-name=ubuntu,
                os-version=24.04
